---

- name: Update and Install Apache2 from APT Repos
  apt: >
    name=apache2
    update_cache=yes
    state=latest
  environment: "{{ proxy_env }}"

- name: Enable/Install Apache2 modules via a2enmod
  apache2_module: name={{ item.name }} state=present
  when: apache2_modules is defined and item.name is defined
  with_items: "{{ apache2_modules }}"
  environment: "{{ proxy_env }}"
  notify:
    - Restart Apache2

- name: Enable/Install Apache2 modules via APT
  apt: >
    name={{ item.package }} update_cache=yes state=latest
  when: apache2_modules is defined and item.package is defined
  with_items: "{{ apache2_modules }}"
  environment: "{{ proxy_env }}"
  notify:
    - Restart Apache2

- name: Ensure Apache has selected state and enabled on boot.
  service: name=apache2 state={{ apache_service_state }} enabled={{ apache_service_startonboot }}
