---

- name: Seed MapProxy Cache
  action: >
      shell mapproxy-seed -f {{ mapproxy_service.config }} -s {{ mapproxy_seed.config }}
      chdir={{ mapproxy_home_dir }}
  when: seed_cache == 'true'
  environment: "{{ proxy_env }}"


# Fix file permissions
- file: path={{ mapproxy_cache_data_dir }} state=directory owner={{ mapproxy_user }} group={{ mapproxy_group }} recurse=yes
  when: mapproxy_cache_data_dir is defined and seed_cache == 'true'
