---
# Install Logstash plugins

# Loop though logstash_plugins and install them
- name: Removing Plugins if they exist
  action: >
    shell bin/logstash-plugin uninstall "{{ item.name }}"
    chdir="{{ logstash_home_dir }}"
  with_items: "{{ logstash_plugins }}"
  ignore_errors: yes

- name: Installing Plugins by Name
  action: >
    shell bin/logstash-plugin install "{{ item.name }}"
    chdir="{{ logstash_home_dir }}"
  with_items: "{{ logstash_plugins }}"
  ignore_errors: yes
  environment: "{{ proxy_env }}"
