---
# defaults file for the ansible-logstash role

logstash_version: "2.2"

logstash_apt_repo: "deb http://packages.elastic.co/logstash/{{ logstash_version }}/debian stable main"
logstash_apt_source_list: "/etc/apt/sources.list.d/logstash-{{ logstash_version }}.list"
logstash_repo_key: "http://packages.elasticsearch.org/GPG-KEY-elasticsearch"

logstash_home_dir: "/opt/logstash/"

logstash_user: logstash
logstash_group: logstash

# sets LS_USER for the init.d startscript in /etc/default/logstash
logstash_defaults: "LS_USER={{ logstash_user }}"

logstash_plugins:
  - { name: 'logstash-filter-prune' }
  - { name: 'logstash-filter-translate' }

logstash_conf_dir: "/etc/logstash/conf.d"
logstash_index_templates_dir: "/etc/logstash/index_templates"

logstash_service_startonboot: no
logstash_service_state: restarted
