---

# Configure Elasticsearch Node
- name: Configuring Elasticsearch Node
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner=root group={{ elasticsearch_group }} mode=0750
  when: elasticsearch_conf_dir is defined


- template: src=elasticsearch.default.j2 dest=/etc/default/elasticsearch owner=root group=root mode=0644
