---

# Handle plugins

# Wait for jenkins to startup, default 10s
- name: "{{ jenkins_startup_delay_s | default(10) }}s delay while starting Jenkins"
  wait_for: host={{ jenkins_host }} port={{ jenkins_port }} delay={{ jenkins_startup_delay_s | default(10) }}
  when: jenkins_install.changed or config_changed.changed

- name: "Create Jenkins CLI destination directory: {{ jenkins_dest }}"
  file: path={{ jenkins_dest }} state=directory

- name: Get Jenkins CLI
  get_url: url=http://{{ jenkins_host }}:{{ jenkins_port }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_var.cli_dest }} mode=0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10

- name: Create Jenkins Update directory
  file:
    path: "/var/lib/jenkins/updates"
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_group }}'
    mode: 0755
    state: directory

# Fix permissions on directories
- name: Fix Permissions
  file:
    path: "{{ jenkins_lib }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    recurse: yes

- name: Update Jenkins plugin data
  shell: >
    curl -L '{{ jenkins_updates_list }}' | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json
  environment: "{{ proxy_env }}"
  always_run: True


- name: Permissions for default.json updates info.
  file:
    path: "/var/lib/jenkins/updates/default.json"
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_group }}'
    mode: 0755
