---

# Configure user and group
- name: Configuring user and group
  group: name={{ jenkins_group }}

- user: name={{ jenkins_user }} group={{ jenkins_group }} createhome=no

# Update repos
- name: Update APT repositories
  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  environment: "{{ proxy_env }}"

- name: Configure the Jenkins APT key
  apt_key: url='{{ jenkins_apt_key }}' state=present validate_certs={{ validate_apt_certificates }}
  environment: "{{ proxy_env }}"

- name: Add Jenkins Repository
  apt_repository: repo='{{ jenkins_deb_repo }}' state=present update_cache=yes
  environment: "{{ proxy_env }}"

- name: Install Jenkins
  apt: name=jenkins update_cache=yes state=latest
  register: jenkins_install
  environment: "{{ proxy_env }}"
